//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariMobil.Models
{
    using System;
    using System.Collections.Generic;



    public class SearchResult
    {
        public SearchResultType ResultType { get; set; }

        public string Message { get; set; }

        public object Data { get; set; }

    }
    public enum SearchResultType
    {
        Success = 1,
        Fail = 2,
        Warn = 3
    }
    public class SearchModel
    {
        public string query { get; set; }

    }



    public class DetayModel
    {
        public Cariler cari { get; set; }
        public List<CariDosyalar> dosyalar { get; set; }
    }
    


    public partial class Cariler
    {
        public int CariId { get; set; }
        public string ad { get; set; }
        public Nullable<System.DateTime> olTarih { get; set; }
        public Nullable<System.DateTime> gunTarih { get; set; }
        public string tel { get; set; }
        public string tel2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public bool sil { get; set; }
        public string cariTip { get; set; }
    }
}
