//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariPersonelBirim
    {
        public int personelBirimID { get; set; }
        public Nullable<int> cariID { get; set; }
        public string personelBirimAdi { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string tel2 { get; set; }
        public string fax { get; set; }
    }
}
