//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariMobil.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobilCariEntities1 : DbContext
    {
        public MobilCariEntities1()
            : base("name=MobilCariEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CariDosyalar> CariDosyalar { get; set; }
        public virtual DbSet<Cariler> Cariler { get; set; }
        public virtual DbSet<CariPersonelBirim> CariPersonelBirim { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
        public virtual DbSet<StokBirimler> StokBirimler { get; set; }
        public virtual DbSet<StokKategoriler> StokKategoriler { get; set; }
        public virtual DbSet<Stoklar> Stoklar { get; set; }
    }
}
