//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoklar
    {
        public int StokID { get; set; }
        public Nullable<int> StokKategoriID { get; set; }
        public string ad { get; set; }
        public string aciklama { get; set; }
        public string gorsel { get; set; }
        public Nullable<int> adet { get; set; }
    }
}
