//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKategoriler
    {
        public int StokKategoriID { get; set; }
        public Nullable<int> ustKategoriID { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> olTarihi { get; set; }
        public string gunTarihi { get; set; }
    }
}
