//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CariMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokBirimler
    {
        public int StokBirimlerID { get; set; }
        public Nullable<int> StoklarID { get; set; }
        public string birim { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    }
}
